### ISSUE TITLE
Export to eps not working in Qt5 version

### ISSUE THREAD

**Issue by KDB2** [veusz/veusz#152]
Hi Jeremy,

In Qt5, the support for ps has been removed. Therefore trying to export in ps format leads to this error: 
.../veusz/document/export.py", line 295, in exportPDFOrPS
    qt4.QPrinter.PostScriptFormat)
AttributeError: type object 'QPrinter' has no attribute 'PostScriptFormat'

See here for a confirmation that ps is no more supported: https://qt.gitorious.org/qt/qtbase/commit/34f712e79e97b757b4426e1ffa09e065c9e379a1

Therefore I see 2 solutions: 
1) Removing the support for ps in veusz. 
2) Using this external library: http://soft.proindependent.com/eps/

I will investigate option 2, but I believe my skills are too low to succeed in this direction. 
In case this external library is interesting to you, please note that the same author has a latex engine too. This could be interesting: http://soft.proindependent.com/qtexengine/

**Comment by jeremysanders** [comment]
Thanks - I hadn't realised it had been removed. I do know some users who use the postscript, so it's a shame to lose it.

That library looks interesting, though I had look through the source code and I can't see how it embeds fonts into the postscript. I think it only uses native fonts. I think it would be hard to get output which looks the same on screen as in the file.

As alternatives to the above library, it might be possible to write a quick postscript engine, though supporting the fonts would be the tricky part (i.e. having characters in the output rather than converting everything to curves first).

There's also the Cairo library which can support many kinds of output, but it wouldn't be trivial to use this.

Perhaps I should ask on this mailing list to see how important postscript is.

**Comment by KDB2** [comment]
ps is of course linked to eps. Therefore we speak about two standard formats for Latex users. 
This said, one can argue that it's easy to transform a pdf into an eps. But it's one more conversion added on top of the stack.
One can also argue that pdf images are well supported and often preferred if you compile your Latex document in pdf. But not all journal/conference accept the pdf produced by pdfLaTex. I had once the case where the dvi file was accepted but not the pdf. 

Therefore these formats seem important. I don't get why Qt decided to kill them.

**Comment by jeremysanders** [comment]
I've decided to use ghostscript if available to convert to EPS/PS. I've integrated this into the program. There's a new setting in the preferences dialog for the ghostscript executable. By default it searches on the PATH for gs or gs.exe.

This commit also fixes bitmap and EMF exports.
