### ISSUE TITLE
Colormaps produce odd result

### ISSUE THREAD

**Issue by MarkDurre** [veusz/veusz#191]
Hi all,
I'm getting funny results from colormaps when I plot an image on log scaling. I attach file with example. I've made 2 colormaps ("heat1" and "heat2") used on the 2 plots, they only differ for the last triple (255,255,**_255_**) vs (255,255,**_254_**); this sets the below minimum background as some sort of gray vs. black (the desired result). This happens only when the LAST triple is (255,255,255); if a triple in the middle of the array is set thus, it looks fine.
[ColormapTest.vsz.zip](https://github.com/veusz/veusz/files/1255819/ColormapTest.vsz.zip)

**Comment by jeremysanders** [comment]
Ok, previous patch wasn't optimal. See this one: https://github.com/veusz/veusz/commit/5e66e9c31f1c73c11ba8a46ba1db17d9e89ab5da

Veusz had several bugs here. It switches between outputs with and without alpha channels, but got the detection wrong (indices were round the wrong way in a check). There's also an issue with the interpolation of alpha values which ends up with values of 254 instead of 255 due to floating point rounding. Hopefully this version fixes all these problems. It checks as the image is being created whether an alpha channel is used. It also rounds RGB values to the nearest integer, rather than truncating.

**Comment by jeremysanders** [comment]
Should be fixed in 1.27.
