### ISSUE TITLE
Import fits files with $FILENAME

### ISSUE THREAD

**Issue by MarkDurre** [veusz/veusz#218]
With version 2+, when I import fits files with prefix $FILENAME, it adds the extension to the end of the dataset name e.g. "MYFITSFILE.FITS" becomes "MYFITSFILE.FITSprimary". How do I revert this to the old behavior without manually editing the dataset name

**Comment by jeremysanders** [comment]
I don't think this is intentional - it's a bug...

**Comment by jeremysanders** [comment]
Actually, it's intended behaviour. The default dataset name for the primary HDU is primary, so that how it acquires the name. Didn't you have to enter a name in the previous version? What would you like to happen?

If you're generating the fits file, you can always add a header keyword called VEUSZ with the value NAME=myname to override the automatic name.

**Comment by MarkDurre** [comment]
Hi Jeremy,

Previously, if I used the $FILENAME prefix, it just gave me the filename “xxxx.fits” – maybe you could have a prefix $EXTN which puts the extension name in (e.g. “$FILENAME$EXTN” would translate to “xxxx.fitsprimary”. Also, I’ve noticed that the default Image WCS mode is “Linear (WCS)”, previously it was “Pixel (Simple)”, and that caused some confusion.

Cheers,

Mark Durré
Ph.D. Student
Centre for Astrophysics and Supercomputing
Swinburne University of Technology
PO Box 218, Hawthorn
Victoria 3122, Australia
Email: mdurre@swin.edu.au<mailto:mdurre@swin.edu.au>

**Comment by jeremysanders** [comment]
$FILENAME isn't being changed, it's just the default name of the dataset which becomes "primary" for the primary HDU.
