### ISSUE TITLE
Transparent border marker of xy type causes error when exporting to EMF.

### ISSUE THREAD

**Issue by SolarNow** [veusz/veusz#226]
Dear Jeremy, 
thanks a lot for this nice piece of software Veusz 2.1.1!  I got to know it only three days back from one of my students and have already generated quite complex and still nice looking graphs with it.  
Just to let you know a small error: I encountered an error when exporting a graph to emf-format. The same graph did not produce an error when exporting it to pdf format. The graph contained an “xy” type. With some trial and error I discovered that the error does no longer occur after changing the color of "Marker border" from "transparent" to any other color, e.g. "red". It appears that the export function to emf does not accept a transparent marker border. 
Hopefully this little information helps you to remove this bug or otherwise it helps other users to work around it. 
Rolf.

**Comment by jeremysanders** [comment]
Thanks for the report. To hide a border, the recommended way is to set the "Hide" setting, rather than use transparency. Transparency isn't supported in EMF format files anyway (according to the Microsoft docs).

There shouldn't cause an error, however. There was an error in the Python 3 handling of embedded bitmaps, which are used to simulate transparency. This will be fixed in the next release.
