### ISSUE TITLE
Can't import HDF5 file when path is too long.

### ISSUE THREAD

**Issue by SuperDiex** [veusz/veusz#316]
Veusz version is 3.0.1.1
I imported some data from a HDF5 file into a .vsz file(data is linked to file). This part goes well. But if the file path is too long(probably longer than 260 characters), then when I close the .vsz file and reopen it, there will be an an import error(No such file or directory).
I found that this can be fixed by using absolute path, which means with this code:
`AddImportPath(u'C:\\Users\\Rubidium\\Documents\\LabView Programs\\数据图\\SPMnBiTe05272019No3')
ImportFileHDF5(u'../../Data/SPMnBiTe05272019No3/EP0604-2019/PVC_8-I-6_2-GND_SPMnBiTe05272019No3_0mV_633White_IR100X_20nA30ms_0604-20/PVC_8-I-6_2-GND_SPMnBiTe05272019No3_0mV_633White_IR100X_20nA30ms_0604-20.h5', [u'/Data-UTF-8/PV-X', u'/Data-UTF-8/PV-Y', u'/Data-UTF-8/Reflection-X', u'/Data-UTF-8/Reflection-Y'], linked=True)
`
this problem will occur.
with this code:
`AddImportPath(u'C:\\Users\\Rubidium\\Documents\\LabView Programs\\数据图\\SPMnBiTe05272019No3')
ImportFileHDF5(u'C:/Users/Rubidium/Documents/LabView Programs/Data/SPMnBiTe05272019No3/EP0604-2019/PVC_8-I-6_2-GND_SPMnBiTe05272019No3_0mV_633White_IR100X_20nA30ms_0604-20/PVC_8-I-6_2-GND_SPMnBiTe05272019No3_0mV_633White_IR100X_20nA30ms_0604-20.h5', [u'/Data-UTF-8/PV-X', u'/Data-UTF-8/PV-Y', u'/Data-UTF-8/Reflection-X', u'/Data-UTF-8/Reflection-Y'], linked=True)
`
this problem is resolved.

If I fix the problem with absolute path, then when I save the .vsz file as a new file, this problem occurs again.
Is there a way to fix this better?

**Comment by jeremysanders** [comment]
Windows has some 260 character restrictions in various places (from MAX_PATH). Veusz doesn't actively constrain the length of the filenames.

This article suggests it may be possible to enable group policy to get longer paths, though maybe a manifest change is requred:
https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/

You could also try prefixing your paths with `\\?\` instead of `\\`
