### ISSUE TITLE
On Windows the installer .exe causes a Windows Defender alert when run.

### ISSUE THREAD

**Issue by loopless** [veusz/veusz#388]
"Windows Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk."

**Comment by jeremysanders** [comment]
Have you tried the 3.2.0.1 version linked from the website? This has a workaround.

**Comment by loopless** [comment]
Yes, I used the latest 3.2.0.1 from the website. 
Is the issue you don't have a code-signing certificate for the installer?
I can force an install, but some organizations might have stricter policies.

**Comment by jeremysanders** [comment]
Ah, I didn't read the message properly - it's just not recognised.

There's no code signing certificate. That would require someone to pay for a certificate or donate money in order to do so. I'm not aware of anyone who provides free certificates.

Maybe eventually enough people will use it to make it pass.

**Comment by loopless** [comment]
I see you are correct about code-signing certificates, its not like getting a https:// certificate from LetsEncrypt.
